Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/01/2022
Var


x, y: inteiro


procedimento soma(A, B: inteiro)
inicio

   limpatela
   escreval("Recebi o valor",A)
   escreval("Recebi o valor",B)
   escreval("A soma vale", A+B)

fimprocedimento

Inicio

      escreva("Digite um valor: ")
      leia(x)
      escreva("Digite um valor: ")
      leia(y)
      soma(X,Y)


Fimalgoritmo