Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/01/2022
Var
// Seção de Declarações das variáveis 
   contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   contador <- 0
   enquanto (contador <= 10) faca
            escreval(contador)
            contador<-contador+1
   fimenquanto     ]
   escreval("Terminei de contar")

Fimalgoritmo