Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/01/2022
Var
// Seção de Declarações das variáveis 
   reais, dolar: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Quantos reais eu tenho? ")
   leia(reais)
   dolar <- reais/2.2
   escreval("Posso ter U$ ", dolar)


Fimalgoritmo