Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/01/2022
Var
// Seção de Declarações das variáveis 
cont, v : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite um valor: ")
   leia(v)
   se(v%2=1) entao
             v<-v-1)
   fimse

   para cont<-v ate 0 passo-2 faca
        escreval(cont)
   fimpara


Fimalgoritmo