Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/01/2022
Var
// Seção de Declarações das variáveis 
   preco, imposto: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Qual o valor do produto? ")
   leia(preco)
   imposto <- (preco*60)/100
   escreval("O imposto será de: ", imposto:4:2)



Fimalgoritmo