Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/01/2022
Var
// Seção de Declarações das variáveis 
v: vetor[1..6] de inteiro
c: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   para c<-1 ate 6 faca
      escreva("digite o ", c,"o. valor: ")
      leia(v[c])
   fimpara
   
     para c<-1 ate 6 faca
      escreva("(", v[c],")")
   fimpara


Fimalgoritmo