Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/01/2022
Var
// Seção de Declarações das variáveis 
   angulo, s: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval("Informe um angulo: ")
   leia(angulo)
   s <- sen(grauprad(angulo))
   escreval("O seno de ", angulo, " e igual a ", s)
   
   
Fimalgoritmo