Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/01/2022
Var


x: inteiro


Procedimento par(A: inteiro)
inicio

   se (A%=0) entao
      escreval("O valor é par")
      senao
           escreval("O valor é impar")
   fimse

fimprocedimento


Inicio

      escreva("Digite um valor: ")
      leia(x)
      par(x)


Fimalgoritmo