Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/01/2022
Var
// Seção de Declarações das variáveis 
c, n, s: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   s<-0
   para c<-1 ate 5 faca
        escreva("Digite um valor: ")
        leia(n)
        s<-s+n
   fimpara
   escreval("A soma dos valores e ",s)


Fimalgoritmo