Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/01/2022
Var
// Seção de Declarações das variáveis 
   a, b, c: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   a <- 2
   b <- 3
   c <- 5

   escreval("A = 2")
   escreval("B = 3")
   escreval("C = 5")
   escreval((A=B) ou (C>A))


   
   
Fimalgoritmo