Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/01/2022
Var
// Seção de Declarações das variáveis 
c: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   para c<-1 ate 10 faca
        escreval(c)
   fimpara
   para c<-10 ate 1 passo -1 faca
        escreval(c)
   fimpara

Fimalgoritmo